language: java
jdk:
  - openjdk8
script:
  - mvn clean install
  - mvn -f ./examples/TransformationTesting/pom.xml package
after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)